export default class billedAtOrder{
    public static subTotal83: string = 'Sub-total￥83'
    public static subTotal85: string = 'Sub-total￥85'
    public static subTotal90: string = 'Sub-total￥90'
    public static subTotal92: string = 'Sub-total￥92'
    public static subTotal94: string = 'Sub-total￥94'
    public static subTotal95: string = 'Sub-total￥95'
    public static subTotal100: string = 'Sub-total￥100'
    public static subTotal180: string = 'Sub-total￥180'
    public static subTotal190: string = 'Sub-total￥190'
    public static subTotal200: string = 'Sub-total￥200'
    public static subTotal270: string = 'Sub-total￥270'
    public static subTotal300: string = 'Sub-total￥300'

    public static oneProduct_TaxIncl5: string = 'Tax (5% incl)￥5'
    public static oneProduct_TaxIncl5TaxAmount4: string = 'Tax (5% incl)￥4'
    public static twoProduct_TaxIncl5TaxAmount10: string = 'Tax (5% incl)￥10'
    public static twoProduct_TaxIncl5TaxAmount9: string = 'Tax (5% incl)￥9'

    public static oneProduct_TaxIncl10: string = 'Tax (10% incl)￥10'
    public static oneProduct_TaxIncl10TaxAmount9: string = 'Tax (10% incl)￥9'
    public static oneProduct_TaxIncl10TaxAmount8: string = 'Tax (10% incl)￥8'
    
    public static total83: string = 'Total￥83'
    public static total85: string = 'Total￥85'
    public static total90: string = 'Total￥90'
    public static total92: string = 'Total￥92'
    public static total94: string = 'Total￥94'
    public static total95: string = 'Total￥95'
    public static total100: string = 'Total￥100'
    public static total180: string = 'Total￥180'
    public static total190: string = 'Total￥190'
    public static total200: string = 'Total￥200'
    public static total270: string = 'Total￥270'
    public static total300: string = 'Total￥300'
}